# This is a basic workflow to help you get started with Actions

name: Build APRSC

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    #inputs:
    #  perform_release:
    #    required: true
    #    type: boolean

  release:
    types: [created]

defaults:
  run:
    shell: bash
    working-directory: ./src

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install dependencies on Debian
        run: |
          echo Update packages ========================================
          sudo apt-get update
          echo Install dependencies ===================================
          sudo apt-get --yes install \
            libevent-dev libsctp-dev libcap-dev \
            lsb-release debhelper
          #echo gcc version before
          #gcc --version
          #sudo apt-get --yes install make gcc g++

      - name: Build DEB package
        run: |
          #cd $GITHUB_WORKSPACE/src
          echo Configure build ========================================
          ./configure
          echo Build DEB package ======================================
          make make-deb

      - name: Upload DEB to Releases
        #if: ${{ inputs.perform_release }}
        if: ${{ github.event.release.tag_name != 0 }}
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
        run: |
          echo Release DEB package ====================================
          gh release upload ${{github.event.release.tag_name}} ../aprsc_*.deb
